'use strict'
import { StyleSheet, Platform } from 'react-native'
import { scale } from '../../styles/sizes'
import { color } from '../../theme'

export const styles = StyleSheet.create({
  buttonDark: {
    backgroundColor: color.palette.HighSlateBlue,
    width: Platform.OS === 'web' ? scale(150) : scale(335),
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 10,
    marginVertical: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  buttonSmall: {
    backgroundColor: color.palette.HighSlateBlue,
    width: scale(173),
    maxWidth: '40%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  buttonThin: {
    backgroundColor: color.palette.HighSlateBlue,
    width: scale(147),
    maxWidth: '40%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  buttonWhite: {
    backgroundColor: color.palette.white,
    width: scale(335),
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  buttonWhiteText: {
    fontSize: 16,
    color: color.palette.HighSlateBlue,
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: 19.36,
  },
  buttonThinText: {
    fontSize: 14,
    color: color.palette.white,
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: 16.59,
  },
  buttonDarkText: {
    fontSize: 16,
    color: color.palette.white,
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: 19.36,
  },
  buttonLoading: { position: 'absolute', justifyContent: 'center', alignItems: 'center' },
  modalFooterButton: {
    backgroundColor: color.palette.orange,
    width: scale(250),
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  modalFooterButtonView: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  modalFooterButtonText: {
    fontSize: 16,
    color: color.palette.white,
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: 19,
    paddingHorizontal: 13,
  },
  modalFooterButtonIcon: { height: 20, width: 20 },
})
