'use strict'
import { StyleSheet, Platform } from 'react-native'
import { moderateScale, scale, verticalScale } from '../styles/sizes'
import { color } from '../theme'

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  containerWhite: {
    flex: 1,
    backgroundColor: color.palette.white,
  },
  viewMain: {
    flex: 1,
    backgroundColor: color.palette.white,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: verticalScale(20),
  },
  viewMainSmall: {
    backgroundColor: color.palette.white,
    marginLeft: Platform.OS === 'web' ? scale(20) : scale(15),
    marginRight: scale(50),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  viewMainLarge: {
    backgroundColor: color.palette.white,
    marginLeft: scale(15),
    marginRight: scale(50),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  viewMainLargeStart: {
    backgroundColor: color.palette.white,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  viewMainLargeEnd: {
    height: verticalScale(80),
    backgroundColor: color.palette.white,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewMainRow: { flexDirection: 'row' },
  viewTopSpace: { marginTop: 20 },
  textLarge: {
    fontSize: 28,
    lineHeight: 33.89,
    color: color.palette.black,
    fontWeight: '700',
    paddingVertical: 5,
    textAlign: 'left',
  },
  textLargeStart: {
    fontSize: 24,
    lineHeight: 29,
    color: color.palette.HighSlateBlue,
    fontWeight: 'bold',
    paddingVertical: 5,
  },
  textMedium: {
    fontSize: 18,
    color: color.palette.HighSlateBlue,
    fontWeight: 'bold',
  },
  titleMediumDark: {
    width: scale(173),
    maxWidth: '40%',
    height: 19,
    color: color.palette.black,
    fontSize: 16,
    lineHeight: 18.96,
    fontWeight: 'bold',
  },
  titleInputDark: {
    height: 19,
    color: color.palette.black,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: 'bold',
    alignSelf: 'flex-start',
    marginVertical: 12,
  },
  titleMediumLight: {
    width: scale(173),
    maxWidth: '40%',
    height: 14,
    color: color.palette.gray,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: 'bold',
  },
  textMediumBold: {
    fontSize: 14,
    color: color.palette.black,
    fontWeight: '500',
  },
  textSmall: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19.36,
    color: color.palette.black,
    textAlign: 'center',
    opacity: 0.6,
  },
  textSmallWithPadding: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19.36,
    color: color.palette.gray,
    textAlign: 'left',
    paddingVertical: 10,
    opacity: 0.6,
  },
  textOuter: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 19.36,
    color: '#666f8a',
    textAlign: 'left',
    paddingVertical: 10,
  },
  bottomContainer: {
    backgroundColor: color.palette.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: scale(335),
    alignSelf: 'center',
  },
  dotContainer: {
    backgroundColor: color.palette.white,
    flexDirection: 'row',
    marginVertical: 52,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dotButtonActive: {
    marginHorizontal: Platform.OS === 'web' ? 5 : scale(10),
    width: 30,
    height: 7,
    borderRadius: 10,
    backgroundColor: color.palette.HighSlateBlue,
  },
  dotButtonInActive: {
    marginHorizontal: 10,
    width: 15,
    height: 7,
    borderRadius: 10,
    backgroundColor: color.palette.gray,
  },
  buttonOnBoarding: {
    backgroundColor: color.palette.HighSlateBlue,
    width: scale(100),
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  buttonDark: {
    backgroundColor: color.palette.HighSlateBlue,
    width: scale(335),
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 15,
  },
  buttonDarkText: {
    fontSize: 16,
    color: color.palette.white,
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: 19.36,
  },
  textInput: {
    width: Platform.OS === 'web' ? scale(150) : scale(335),
    height: 50,
    borderRadius: 10,
    backgroundColor: color.palette.lighterGrey,
    color: color.palette.black,
    borderBottomWidth: 0,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 19,
    marginTop: 15,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  searchInput: {
    width: Platform.OS === 'web' ? scale(150) : scale(335),
    height: 50,
    borderRadius: 10,
    backgroundColor: color.palette.lighterGrey,
    color: color.palette.black,
    borderBottomWidth: 0,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 19,
    marginTop: 15,
    marginBottom: 20,
    overflow: 'hidden',
  },
  textInputBox: {
    width: scale(300),
    height: 50,
    backgroundColor: 'transparent',
    fontSize: 30,
    fontWeight: 'bold',
    lineHeight: 36,
    marginVertical: 30,
    paddingHorizontal: 10,
    marginLeft: Platform.OS === 'ios' ? scale(60) : 0,
    paddingVertical: 2,
    letterSpacing: 28,
  },
  textCover: {
    position: 'absolute',
    backgroundColor: color.palette.white,
    width: scale(355),
    height: 50,
    lineHeight: 36,
    marginVertical: 30,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  textCoverBox: {
    width: 30,
    height: 50,
    borderBottomColor: color.palette.lightGrey,
    borderBottomWidth: 2,
    paddingHorizontal: 21,
    marginHorizontal: 2,
  },
  linkText: {
    textDecorationLine: 'underline',
    fontSize: 14,
    lineHeight: 17,
    color: color.palette.black,
    textDecorationColor: color.palette.black,
  },
  linkTextDanger: {
    textDecorationLine: 'underline',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 18.96,
    color: color.palette.HighSlateBlue,
    textDecorationColor: color.palette.HighSlateBlue,
  },
  errorText: { color: color.palette.angry, fontSize: 10 },
  error: {
    color: color.palette.angry,
    marginTop: -15,
    paddingBottom: 10,
    alignSelf: 'flex-start',
    marginLeft: Platform.OS === 'web' ? scale(113) : 20,
  },
  bottomTextContainer: {
    backgroundColor: color.palette.white,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'ios' ? 10 : 25,
  },
  bottomViewContainer: { flex: 1, justifyContent: 'flex-end', alignItems: 'center' },
  headerContainerMain: {
    paddingVertical: 15,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerContainerCenterText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 17,
    color: color.palette.black,
    textAlign: 'center',
  },
  headerContainerCenterImage: { height: 40, width: 80 },
  headerContainerLeftImage: { height: 20, width: 20 },
  headerContainerRightImage: { height: 20, width: 22.5 },
  headerContainerBackImage: { height: 12, width: 6 },
  headerContainerBackText: { paddingHorizontal: 10, fontSize: 16, fontWeight: '500', lineHeight: 19 },
  videoMainView: {
    width: scale(376),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  homeBottomView: {
    alignItems: 'center',
    width: scale(375),
    height: 115,
    backgroundColor: color.palette.white,
    justifyContent: 'flex-end',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  addButtonView: { position: 'absolute', bottom: 45 },
  addButtonIcon: {
    width: 74,
    height: 74,
    resizeMode: 'contain',
  },
  buttonContainerMain: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonContainerImage: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
    marginVertical: 12,
  },
  buttonContainerText: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 15,
    color: color.palette.white,
  },
  cardPointsView: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-evenly', width: '100%' },
  cardRow: { flexDirection: 'row', marginLeft: 15 },
  cardLayout: { width: moderateScale(48), height: moderateScale(72), backgroundColor: '#686D96', marginLeft: 2 },
  cardImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  cardActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'flex-end',
    width: '100%',
    marginTop: 8,
  },
  cardActionRow: { flexDirection: 'row', marginRight: 25 },
  cardRightActionLayout: {
    transform: [{ rotate: '10deg' }],
    width: moderateScale(84.5),
    height: moderateScale(126.24),
    marginLeft: -10,
    shadowColor: 'black',
    shadowOffset: {
      width: 4,
      height: 1,
    },
    shadowRadius: 4,
  },
  cardLeftActionLayout: {
    transform: [{ rotate: '-5deg' }],
    width: moderateScale(84.5),
    height: moderateScale(126.24),
  },
  loadingIndicator: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color.palette.lighterGrey,
    opacity: 0.5,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  pickerPlaceholder: { color: color.palette.gray },
  pickerContainer: {
    backgroundColor: color.palette.lighterGrey,
    width: Platform.OS === 'web' ? scale(150) : scale(335),
    height: verticalScale(120),
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  pickerStyle: {
    backgroundColor: color.palette.lighterGrey,
    width: Platform.OS === 'web' ? scale(150) : scale(335),
    height: 50,
    alignSelf: 'center',
    flexDirection: 'row',
    borderColor: color.palette.lighterGrey,
    borderBottomWidth: 0,
    paddingHorizontal: 20,
  },
  fullHeight: { height: verticalScale(812) },
  fullWidth: { width: scale(375) },
  logo: { flex: 1, resizeMode: 'contain' },
})
